[versions]
java = "11"
kotlin = "1.8.10"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "1.6.20" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "10.2.1" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.19.0" }
plugin-publish = { id = "com.gradle.plugin-publish", version = "1.1.0" }
versions = { id = "com.github.ben-manes.versions", version = "0.42.0" }

[libraries]
android-plugin = { module = "com.android.tools.build:gradle", version = "3.6.4" }
commons = { module = "org.apache.commons:commons-csv", version = "1.9.0" }
moshi = { module = "com.squareup.moshi:moshi", version = "1.13.0" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version = "0.7.5" }
maven-model = { module = "org.apache.maven:maven-model", version = "3.8.5" }
spock = { module = "org.spockframework:spock-junit4", version = "2.1-M2-groovy-3.0" }
xmlunit = { module = "org.xmlunit:xmlunit-matchers", version = "2.9.0" }
