[versions]
java = "11"
kotlin = "1.9.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "1.8.20" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.5.1" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.25.3" }
plugin-publish = { id = "com.gradle.plugin-publish", version = "1.2.1" }
versions = { id = "com.github.ben-manes.versions", version = "0.47.0" }

[libraries]
android-plugin = { module = "com.android.tools.build:gradle", version = "8.1.1" }
commons = { module = "org.apache.commons:commons-csv", version = "1.10.0" }
moshi = { module = "com.squareup.moshi:moshi", version = "1.15.0" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version = "0.9.1" }
maven-model = { module = "org.apache.maven:maven-model", version = "3.9.4" }
spock = { module = "org.spockframework:spock-junit4", version = "2.4-M1-groovy-3.0" }
xmlunit = { module = "org.xmlunit:xmlunit-matchers", version = "2.9.1" }
