[versions]
junit = "6.0.2"
kotlin = "2.3.10"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.3.0" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }
plugin-publish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }
license = { id = "com.jaredsburrows.license", version = "0.9.8" }

[libraries]
android-plugin = { module = "com.android.tools.build:gradle", version = "7.2.2" }
commons = { module = "org.apache.commons:commons-csv", version = "1.14.1" }
moshi = { module = "com.squareup.moshi:moshi", version = "1.15.2" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "6.0.2" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version = "0.12.0" }
maven-model = { module = "org.apache.maven:maven-model", version = "3.9.11" }
spockcore = { module = "org.spockframework:spock-core", version = "2.4-groovy-4.0" }
spock-junit4 = { module = "org.spockframework:spock-junit4", version = "2.4-groovy-4.0" }
xmlunit = { module = "org.xmlunit:xmlunit-matchers", version = "2.11.0" }
