[versions]
kotlin = "2.1.20"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.2.0" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.30.0" }
plugin-publish = { id = "com.gradle.plugin-publish", version = "1.3.1" }
versions = { id = "com.github.ben-manes.versions", version = "0.52.0" }
license = { id = "com.jaredsburrows.license", version = "0.9.8" }

[libraries]
android-plugin = { module = "com.android.tools.build:gradle", version = "8.9.1" }
commons = { module = "org.apache.commons:commons-csv", version = "1.14.0" }
moshi = { module = "com.squareup.moshi:moshi", version = "1.15.2" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version = "0.12.0" }
maven-model = { module = "org.apache.maven:maven-model", version = "3.9.9" }
spock = { module = "org.spockframework:spock-junit4", version = "2.4-M5-groovy-3.0" } # 2.4-M5-groovy-4.0
xmlunit = { module = "org.xmlunit:xmlunit-matchers", version = "2.10.0" }
